### ISSUE TITLE
^ [TODO]: Update git initialization (crack-eggs.ps1)

### ISSUE THREAD

**Issue by jkarstin** [jkarstin/GitGhost#1]
### Updates to make
- [x] Rename default `master` branch to `stable`
- [x] Create `alpha` branch with `stable` upstream
- [x] Create `dev` branch with `alpha` upstream
- [x] End with `stable` branch checked out
